package com.mixotc.imsdklib.error;

public interface ErrorType {
    int ERROR_EXCEPTION_NO_ERROR = 0;
    int ERROR_EXCEPTION_UNKNOWN_ERROR = -1;
    int ERROR_EXCEPTION_SERVICE_NOT_RUNNING = -2;
    int ERROR_EXCEPTION_SERVICE_ERROR = -3;
    int ERROR_EXCEPTION_EMPTY_PHONE_NUMBER_OR_EMAIL = -1000;
    int ERROR_EXCEPTION_EMPTY_USERNAME = -1001;
    int ERROR_EXCEPTION_LOGIN_ERROR = -1002;
    int ERROR_EXCEPTION_SERVER_CONNECTION = -1003;
    int ERROR_EXCEPTION_UNABLE_CONNECT_TO_SERVER = -1004;
    int ERROR_EXCEPTION_UNKNOWN_SERVER_HOST = -1005;
    int ERROR_EXCEPTION_SEND_CODE_ERROR = -1006;
    int ERROR_EXCEPTION_NO_CONNECTION_ERROR = -1007;
    int ERROR_EXCEPTION_NO_LOGIN_ERROR = -1008;
    int ERROR_EXCEPTION_SERVER_RESPONSE_ERROR = -1009;
    int ERROR_EXCEPTION_UNEXPECTED_RESPONSE_ERROR = -1010;
    int ERROR_EXCEPTION_EMPTY_USERNAME_OR_PHONE = -1011;
    int ERROR_EXCEPTION_EMPTY_KEYWORD = -1012;
    int ERROR_EXCEPTION_NOT_FRIEND = -1013;
    int ERROR_EXCEPTION_EMPTY_MESSAGE = -1014;
    int ERROR_EXCEPTION_FILE_NOT_EXIST = -1015;
    int ERROR_EXCEPTION_FILE_SIZE_ZERO = -1016;
    int ERROR_EXCEPTION_FILE_UPLOAD_ERROR = -1017;
    int ERROR_EXCEPTION_GROUP_NOT_FOUND = -1018;
    int ERROR_EXCEPTION_GROUP_NOT_OWN = -1019;
    int ERROR_EXCEPTION_NOT_IN_GROUP = -1020;
    int ERROR_EXCEPTION_INVALID_PHONE_NUMBER = -1021;
    int ERROR_EXCEPTION_INVALID_EMAIL = -1022;
    int ERROR_EXCEPTION_EMPTY_CODE = -1023;
    int ERROR_EXCEPTION_CODE_EXPIRED = -1024;
    int ERROR_EXCEPTION_FILE_SIZE_TOO_LARGE = -1025;
    int ERROR_EXCEPTION_FILE_NOT_SUPPORT = -1026;
    int ERROR_EXCEPTION_ALREADY_FRIEND = -1027;

    //SERVER ERROR
    int ERROR_EXCEPTION_UNKNOWN = 1;  // 未知错误
    int ERROR_EXCEPTION_DBERROR = 2; // 数据库错误

    int ERROR_EXCEPTION_CODESENT = 3; // 刚发过确认码，还未超时
    int ERROR_EXCEPTION_OVERTIME = 4;    // 验证超时
    int ERROR_EXCEPTION_CODEINVALID = 5; // 验证码失效
    int ERROR_EXCEPTION_VERIFYFAIL = 6; // 谷歌验证失败
    int ERROR_EXCEPTION_PASSERROR = 7; //密码错误
    int ERROR_EXCEPTION_CODEERROR = 8; //验证码错误
    int ERROR_EXCEPTION_OTHERLOGIN = 9; // 有别的设备已登录，针对重连

    int ERROR_EXCEPTION_ORDERTOSELF = 10;      // 下单给自己
    int ERROR_EXCEPTION_ORDERNOENOUGH = 11;    // 卖家(对方)电子币不足
    int ERROR_EXCEPTION_ORDERNOPUBLISH = 12;   // 买家(对方)有订单未完成
    int ERROR_EXCEPTION_ORDERNOTFINISH = 13;   // 买家有订单未完成
    int ERROR_EXCEPTION_ORDERCANCELFIVE = 14;     // 当天取消订单超过5次
    int ERROR_EXCEPTION_ORDERCANCELFIVEO = 15;    // 对方当天取消订单超过5次
    int ERROR_EXCEPTION_ORDERCANCELNOTBUYER = 16; // 只有买家可以取消订单
    int ERROR_EXCEPTION_ORDERNOENOUGHSELF = 17;        // 买家(你自己)电子币不足
    int ERROR_EXCEPTION_ORDERNOTFINIDHSELF = 18;     // 买家(你自己)有订单未完成

    int ERROR_EXCEPTION_ORDERNOTONSALE = 19;      // 重建订单 广告已下架

    int ERROR_EXCEPTION_SALENOENOUGH = 20; // 发布出售,电子币不足
    int ERROR_EXCEPTION_SALETHREE = 21;    // 最多可同时发布3条广告
    int ERROR_EXCEPTION_SALE_COIN_TWO = 22;    // 一个币种只能发一个广告
    int ERROR_EXCEPTION_SALE_NO_LARGE = 24;    // 大额申请未通过

    // 提币
    int ERROR_EXCEPTION_WITHDRAWPASSERROR = 30; // 提币密码错误
    int ERROR_EXCEPTION_WITHDRAWZERO = 31;      // 钱包余额小于0
    int ERROR_EXCEPTION_WITHDRAWNOENOUGH = 32;  // 钱包金额不足
    int ERROR_EXCEPTION_WITHDRAW_LESS_LIMIT = 33; // 小于提币限额

    int ERROR_EXCEPTION_RATENOSUCHORDER = 41; // 无此订单
    int ERROR_EXCEPTION_RATEBOTH = 42;        // 双方已评价
    int ERROR_EXCEPTION_RATENOTFIN = 43;     // 订单未完成
    int ERROR_EXCEPTION_RATEBADSELLER = 44;   // 卖家ID错误
    int ERROR_EXCEPTION_RATEDBUYER = 45;      // 买家已评价
    int ERROR_EXCEPTION_RATEBADBUYER = 46;    // 买家ID错误
    int ERROR_EXCEPTION_RATEDSELLER = 47;     // 卖家已评价
    int ERROR_EXCEPTION_RATENOTUORDER = 48;   // 不是你的订单

    // 担保转账
    int ERROR_EXCEPTION_SECURETOSELF = 50;    // 下单给自己
    int ERROR_EXCEPTION_SECURENOTTRADER = 51; // 不是买家也不是卖家
    int ERROR_EXCEPTION_SECURENOTENOUGH = 52; // 电子币不足
    int ERROR_EXCEPTION_SECURENOTFINISH = 53; // 有未完成的担保转账
    int ERROR_EXCEPTION_SECUCANCELNOTRECEIVER = 54; // 只有接收方可以取消
    int ERROR_EXCEPTION_SECUSTATEERROR = 55;        // 状态不匹配
    // 转账
    int ERROR_EXCEPTION_TRANTOSELF = 60;    // 下单给自己
    int ERROR_EXCEPTION_TRANNOTENOUGH = 61; // 电子币不足
    int ERROR_EXCEPTION_TRANNOTYOURS = 62;  // 不是转给你的
    int ERROR_EXCEPTION_TRANVALID = 63;     // 状态无效
    int ERROR_EXCEPTION_TRANOVERTIME = 64;  // 超时,24小时
    // 红包
    int ERROR_EXCEPTION_GIFTNOTENOUGH = 71; // 电子币不足
    int ERROR_EXCEPTION_GIFTOVERTIME = 72;  // 超过24小时
    int ERROR_EXCEPTION_GIFTNOTMEMBER = 73; // 不是组成员
    int ERROR_EXCEPTION_GIFTNOLEFT = 74;    // 红包领完
    int ERROR_EXCEPTION_GIFTTAKED = 75;    // 已经领过红包

    // 其他
    int ERROR_EXCEPTION_CREATE_COIN = 82; // 创建币种失败
    int ERROR_EXCEPTION_NOTRUSTSELF = 90; // 不能信任自己
    int ERROR_EXCEPTION_PASSSAME = 91;    // 重置密码，新旧密码相同
    int ERROR_EXCEPTION_PASSEMPTY = 92;   // 重置密码，密码为空
    int ERROR_EXCEPTION_NAMEUSED = 93;    // 修改昵称，名字已占用
    int ERROR_EXCEPTION_FRIENDTWICE = 94; // 好友请求，已经是好友了
    int ERROR_EXCEPTION_APPEALNOTYOUR = 96; // 不是你的申诉
    int ERROR_EXCEPTION_AREADY_HAD_WALLET = 97; // 该钱包已创建
    int ERROR_EXCEPTION_PRICE_CHANGED = 98;//下单时对方价格改变
    int ERROR_VERIFY_THREE = 100;// 身份认证失败超过3次
    int ERROR_VERIFY_ING = 101; // 正在审核中
    int ERROR_IDENTITY_STATE_UNKNOWN = 102; // 身份认证状态不识别
    int ERROR_IDENTITY_ALREADY_PASS = 103; // 身份认证已经通过
    int ERROR_IDENTITY_STATE_WRONG = 104; // 身份认证状态不是待审核不能修改
    int ERROR_IDENTITY_NOT_FOUND = 105; // 身份认证记录不存在
    int ERROR_IVERIFY_PAUSE = 106; // 恶意上传，关闭上传功能三天

    // 客服
    int ERROR_NOT_ADMIN = 110; // 非管理员
    int ERROR_APPEAL_WAS_ARBITRATED = 111; // 已完成仲裁
    int ERROR_APPEAL_WAS_CANCEL = 112; // 申诉已撤回
    int ERROR_APPEAL_NO_RESPONSIBLE = 113; // 未指定责任人
    int ERROR_APPEAL_STATUS_INVALID = 114;  // 申诉状态不匹配
    int ERROR_APPEAL_SHOULD_WAITTING = 115; // 需付款三十分钟后才可申诉

    int ERROR_LOGIN_CODE_INNER_THIRTY = 201; // 三十分钟内验证码
}
